# left-side user profile
avatar: # by default https://octodex.github.com/images/baracktocat.jpg
location:
email:
social:
  github:
  weibo:
  linkedin:

# navbar menu
menu:
 archives: true
 tags: true
 categories: true

tag_dir: tags
archive_dir: archives
category_dir: categories
rss_dir: atom.xml

#marked setting for markdown
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: # baidutongji tracking code
duoshuo: # duoshuo username
gcs: b7b76ca49a2c24082 # google custom search code

# flagcounter
flagcounter_href: # https://info.flagcounter.com/xxxx
flagcounter_img_src: # https://s01.flagcounter.com/xxxx
